spring:
  application:
    name: library
  h2:
    console.enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 9090
  error:
    whitelabel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    logfile:
      enabled: true

  info:
    env:
      enabled: false
    git:
      mode: full

  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: false
logging:
  file:
    name: ./spring-homework-12/logs/log-file.log

eureka:
  client.service-url:
    defaultZone: http://localhost:9001/eureka
    register-with-eureka: true
    fetch-registry: true

  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

